name: Build Delfinovin (Release Only)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      SOLUTION_NAME: Delfinovin.sln
      CONFIGURATION: Release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Restore Solution
        run: msbuild "$env:SOLUTION_NAME" /t:Restore /p:Configuration=$env:CONFIGURATION

      - name: Build Solution
        run: msbuild "$env:SOLUTION_NAME" /p:Configuration=$env:CONFIGURATION

      - name: List Output Folder (Debug)
        run: Get-ChildItem -Path .\bin\Release\net7.0-windows\ -Recurse | ForEach-Object { $_.FullName }

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DelfinovinBuild
          path: ./bin/Release/net7.0-windows/
